# Generated by Django 4.1 on 2022-08-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_post_upvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvotes',
            new_name='likes',
        ),
    ]
