# Generated by Django 4.1 on 2023-02-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
