# Generated by Django 4.1 on 2023-02-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images'),
        ),
    ]
