# Generated by Django 4.1 on 2023-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_post_number_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
