# Generated by Django 4.1 on 2023-02-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_userprofile_follower_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follower_count',
        ),
    ]
